139,140c139,140
< BACKLIGHT_ENABLE = yes	# Enable keyboard backlight functionality
< KEYMAP_IN_EEPROM_ENABLE = yes # Read keymap from eeprom
---
> #BACKLIGHT_ENABLE = yes	# Enable keyboard backlight functionality
> #KEYMAP_IN_EEPROM_ENABLE = yes # Read keymap from eeprom
142,146c142,146
< SOFTPWM_LED_ENABLE = yes # Enable SoftPWM to drive backlight
< FADING_LED_ENABLE = yes # Enable fading backlight
< BREATHING_LED_ENABLE = yes # Enable breathing backlight
< LEDMAP_ENABLE = yes		# Enable LED mapping
< LEDMAP_IN_EEPROM_ENABLE = yes # Read LED mapping from eeprom
---
> #SOFTPWM_LED_ENABLE = yes # Enable SoftPWM to drive backlight
> #FADING_LED_ENABLE = yes # Enable fading backlight
> #BREATHING_LED_ENABLE = yes # Enable breathing backlight
> #LEDMAP_ENABLE = yes		# Enable LED mapping
> #LEDMAP_IN_EEPROM_ENABLE = yes # Read LED mapping from eeprom
